name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir _build
        cd _build
        cmake ..
        cmake --build . --config RelWithDebInfo
    - name: Prepare output
      run: |
        mkdir _output
        cp _build/RelWithDebInfo/cngeant.exe _output
        cp _build/RelWithDebInfo/cngeant.pdb _output
    - name: Upload binaries
      uses: actions/upload-artifact@v1.0.0
      with:
        name: cngeant
        path: _output
